name: Visitor CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up node enviroment
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Build artifact
        run: |
          echo "Building..."
          npm ci 
          npm run build

  push-to-docker-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Login to docker hub
        run: |
          docker --version
        # uses: docker/login-action@v3
        # with:
        #   username: ${{vars.DOCKER_USERNAME}}
        #   password: ${{secrets.DOCKER_PASSWORD}}
