name: Visitor CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up node enviroment
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Build artifact
        run: |
          echo "Building..."
          npm ci 
          npm run build

  push-to-docker-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Build docker image
        run: |
          docker build -t AlexRamosGlz/visitor:1.0 .
        
      - name: publish image to docker hub
        run:  |
          docker login -u ${{vars.DOCKER_USERNAME}} -p ${{secrets.DOCKER_TOKEN}}
          docker push AlexRamosGlz/visitor:1.0
